### ISSUE TITLE
Architecture thoughts

### ISSUE THREAD

**Issue by UCLGuichard** [UCLGuichard/yaml-cpp#21]
Usage outlines
```cpp
YamlParser config_parser("path/to/config/yaml");

my_variable = config_parser.getBlock("measureOperators")["subSection"]["parameter"].as<int>();

my_variable = config_parser.getConfig()["section"]["parameter"].as<bool>();

wavelets = config_parser.getWavelets();
```
With YAML file:
```yaml
measureOperators:
    subSection:
        parameter: 123
section:
    parameter: true
```

Implementation header:
```cpp
/** docs */
class YamlParser {
public:
    const YAML::Node& getBlock(const std::string& name);
    const YAML::Node& getConfig();
private:
    YAML::Node config;
};
```

Source:
```cpp
YAML::Node YamlParser::getConfig()
{
    return this->config;
}

YAML::Node YamlParser::getBlock(const std::string& name)
{
    if (!this->config[name])
        throw ....;
    return this->config[name];
}
```
